format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_E54_PIM_MC_Board, bsp: 'true'}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: BSP_BOARD_SEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: dsPICDEM MCHV-3}
  - type: Float
    attributes: {id: BSP_IA_GAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '10.06'}
  - type: Float
    attributes: {id: BSP_IA_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '1.65'}
  - type: Integer
    attributes: {id: BSP_IA_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '9'}
  - type: Float
    attributes: {id: BSP_IA_SHUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '0.01'}
  - type: Float
    attributes: {id: BSP_IB_GAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '10.06'}
  - type: Float
    attributes: {id: BSP_IB_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '1.65'}
  - type: Integer
    attributes: {id: BSP_IB_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '19'}
  - type: Float
    attributes: {id: BSP_IB_SHUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '0.01'}
  - type: Float
    attributes: {id: BSP_VDC_BOTTOM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '2.2'}
  - type: Integer
    attributes: {id: BSP_VDC_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '13'}
  - type: Float
    attributes: {id: BSP_VDC_TOP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '300.0'}
  - type: Integer
    attributes: {id: BSP_VPOT_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '23'}
  - type: Integer
    attributes: {id: MCBSP_ENCODER_QEA_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '70'}
  - type: Integer
    attributes: {id: MCBSP_ENCODER_QEB_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '71'}
  - type: Integer
    attributes: {id: MCBSP_PWMAH_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '33'}
  - type: Integer
    attributes: {id: MCBSP_PWMAL_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '66'}
  - type: Integer
    attributes: {id: MCBSP_PWMBH_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '34'}
  - type: Integer
    attributes: {id: MCBSP_PWMBL_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '67'}
  - type: Integer
    attributes: {id: MCBSP_PWMCH_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '35'}
  - type: Integer
    attributes: {id: MCBSP_PWMCL_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '68'}
  - type: Integer
    attributes: {id: MCPMSMFOC_BUTTON0_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '47'}
  - type: Integer
    attributes: {id: MCPMSMFOC_LED0_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '103'}
  - type: Integer
    attributes: {id: MCPMSMFOC_LED1_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '102'}
  - type: Float
    attributes: {id: MCPMSMFOC_VOLTAGE_MAGNITUDE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E54_PIM_MC_Board, value: '325.0'}
- type: ElementPosition
  attributes: {x: '106', y: '539', id: BSP_SAM_E54_PIM_MC_Board}
