format_version: v1.0
configName: mclv2_sam_e54_pim
folderName: mclv2_sam_e54_pim
frameworkPath: D:\Release
processor: ATSAME54P20A
projectName: mclv2_sam_e54_pim
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME54_DFP\3.7.122\atdf\ATSAME54P20A.atdf
