format_version: v1.0
type: UniqueComponent
attributes: {id: X2CScope}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: X2C_COMM_INSTANCE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: SERCOM2}
  - type: String
    attributes: {id: X2C_COMM_INSTANCE_RECEIVE_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: '13'}
  - type: Combo
    attributes: {id: X2C_COMM_INSTANCE_RECEIVE_SERCOM0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: X2C_COMM_INSTANCE_RECEIVE_SERCOM2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: PA13}
  - type: String
    attributes: {id: X2C_COMM_INSTANCE_TRANSMIT_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: '12'}
  - type: Combo
    attributes: {id: X2C_COMM_INSTANCE_TRANSMIT_SERCOM0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: X2C_COMM_INSTANCE_TRANSMIT_SERCOM2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: PA12}
  - type: String
    attributes: {id: X2C_SCOPE_PERIPH_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: SERCOM2_USART}
  - type: String
    attributes: {id: X2C_SCOPE_UART_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: sercom2}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: x2cScopeUartDependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom2}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM2_UART}
  - type: DirectCapability
    attributes: {id: x2cScope_Scope}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: pmsm_foc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: pmsmfoc_X2CSCOPE}
- type: ElementPosition
  attributes: {x: '133', y: '372', id: X2CScope}
