format_version: v1.0
type: UniqueComponent
attributes: {id: pdec}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ENCODER_POS_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: PDEC_QDECPositionGet}
  - type: String
    attributes: {id: ENCODER_POS_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: ''}
  - type: String
    attributes: {id: ENCODER_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: PDEC_QDECStart}
  - type: String
    attributes: {id: ENCODER_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: PDEC_QDECStop}
  - type: Integer
    attributes: {id: PDEC_CC0_ANGULAR}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: PDEC_CC0_REVOLUTION}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '0'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: PDEC_CC1_ANGULAR}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: PDEC_CC1_REVOLUTION}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '0'}
  - type: Integer
    attributes: {id: PDEC_CTRLA_ANGULAR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '16'}
  - type: Hex
    attributes: {id: PDEC_CTRLA_ANGULAR_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '65535'}
  - type: Boolean
    attributes: {id: PDEC_CTRLA_PEREN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: PDEC_CTRLA_REVOLUTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '0'}
  - type: Hex
    attributes: {id: PDEC_CTRLA_REVOLUTION_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '0'}
  - type: Hex
    attributes: {id: PDEC_EVCTRL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '0'}
  - type: Integer
    attributes: {id: PDEC_FILTER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: PDEC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '3000000'}
  - type: Combo
    attributes: {id: PDEC_INDEX}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Disabled}
  - type: Hex
    attributes: {id: PDEC_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '3'}
  - type: Hex
    attributes: {id: PDEC_PIN_INV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '0'}
  - type: Comment
    attributes: {id: PDEC_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****PDEC Counter resolution is 333.333333333 nS****'}
- type: ElementPosition
  attributes: {x: '437', y: '232', id: pdec}
