configName: mchv3_sam_e54_pim
folderName: ''
format_version: v1.0
frameworkPath: ../../../GIT_MotorControl
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;csp_apps_pic32mk;motor_control;tflite;training;x2c;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.4.70\atdf\ATSAME54P20A.atdf
