configName: mclv2_sam_e54_pim
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: motor_control;csp;motor_control;x2c;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.4.70\atdf\ATSAME54P20A.atdf
  MERGE_STRATEGY: USER_ALL
