format_version: v1.0
type: UniqueComponent
attributes: {id: tc2}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: COMPARE_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_Timer32bitCompareSet}
  - type: String
    attributes: {id: COUNTER_GET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_Timer32bitCounterGet}
  - type: String
    attributes: {id: PERIOD_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_Timer32bitPeriodSet}
  - type: Boolean
    attributes: {id: TC_CAPTURE_CTRLA_CAPTEN1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: TC_CAPTURE_CTRLA_COPEN0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: TC_CAPTURE_CTRLA_COPEN1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TC_CAPTURE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: TC_CAPTURE_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TC_CAPTURE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TC_CAPTURE_TRIGGER_ACTION0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: TC_CAPTURE_TRIGGER_EDGE1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Long
    attributes: {id: TC_COMPARE_CC0}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '4294967295'}
    - type: Values
      children:
      - type: User
        attributes: {value: '200000'}
  - type: Long
    attributes: {id: TC_COMPARE_CC1}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '200000'}
  - type: Boolean
    attributes: {id: TC_COMPARE_EVCTRL_EV}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: TC_COMPARE_EVCTRL_EVACT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: TC_COMPARE_EVCTRL_TCINV}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TC_COMPARE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Long
    attributes: {id: TC_COMPARE_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '4294967295'}
  - type: Comment
    attributes: {id: TC_COMPARE_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Compare Period is 6666.66666667 us ****'}
  - type: File
    attributes: {id: TC_COMPARE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: TC_CTRLA_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: TC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '30000000'}
  - type: Combo
    attributes: {id: TC_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Capture}
  - type: Comment
    attributes: {id: TC_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Timer resolution is 33.3333333333 nS****'}
  - type: File
    attributes: {id: TC_TIMER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: TC_TIMER_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Long
    attributes: {id: TC_TIMER_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '4294967295'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '30000'}
  - type: File
    attributes: {id: TC_TIMER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Float
    attributes: {id: TC_TIMER_TIME_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '143165.58'}
  - type: String
    attributes: {id: TIMER_PERIOD_MAX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '4294967295'}
  - type: Integer
    attributes: {id: TIMER_WIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '32'}
- type: ElementPosition
  attributes: {x: '409', y: '234', id: tc2}
